### ISSUE TITLE
API dependency?

### ISSUE THREAD

**Issue by ablwr** [europeana/europeana-blacklight#24]
Hi! Following the rules as written in the quickstart, I've gotten the error of "uninitialized constant Europeana::API" on initial load of the Rails server. Is there another dependency required in order to get this running, such as setting an API secret key credential within the application or a system install of the europeana-api Ruby client?

Thanks much!

Ashley

**Comment by rwd** [comment]
Hi Ashley,

Thank you for reporting this issue.

Could you try following the quick start guide again, noting that I have updated the line to be added to your app's Gemfile to be:

`gem 'europeana-blacklight', '~> 0.3', '< 0.4'`

This is because the 0.4 version uses Blacklight 6, but needs its install generator updated to take into account all the changes in Blacklight 6's own install generator.

**Comment by ablwr** [comment]
Thanks! Yeah, I noticed the Europeana install would want to overwrite in a couple of places and ask for permission to do so. My first attempt didn't specify a gem edition and was using the 0.4 version. But I will give this a shot after work today and report back! Thanks for the quick response!

**Comment by rwd** [comment]
The older versoin will still ask to overwrite the blacklight.yml and catalog_controller.rb, which is fine if you have created a new application from scratch. I will add this as a comment to the quickstart. Hope you get it working!

**Comment by ablwr** [comment]
Ah ah ah! Totally and quickly resolved! Thanks very much for the clarification.
